# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk14

services:
  - postgresql

env:
  global:
    - CODECOV_TOKEN="c31409b1-801c-4b69-b385-fc49a81d1372"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту laiwiense@gmail.com
notifications:
  email:
    recipients:
      -laiwiense@gmail.com
    on_success: never # default: change
    on_failure: always # default: always