POST http://localhost:8083/authenticate
Content-Type: application/json

{
  "username": "Kirin",
  "password": "password"
}

###

GET http://localhost:8083/api/person/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLaXJpbiIsImV4cCI6MTYxMjQ3NzM4MiwiaWF0IjoxNjEyNDU5MzgyfQ.G5QmoNUqTE_KQW8IBXdy7S7HfaeREoYzaxwf58a8PfNquNMuz-ZPdlXypjvNN7WscNpg_7wikfPiRG8PW1UHow

###